[package]
name = "keep-a-changelog-parser"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
codespan = "0.9.2"
codespan-reporting = "0.9.2"
semver = "0.9.0"
chrono = "0.4.11"
pulldown-cmark = "0.7.0"

